export const CHANGE_THEME = 'CHANGE_THEME';
export const SELECT_REGION = 'SELECT_REGION'; 
export const LOAD_ALL_DATA = 'LOAD_ALL_DATA';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const LOAD_COUNTRY_DETAIL = 'LOAD_COUNTRY_DETAIL';
export const LOAD_COUNTRY_DETAIL_SUCCESS = 'LOAD_COUNTRY_DETAIL_SUCCESS';
export const LOAD_COUNTRY = 'LOLOAD_COUNTRY';